#!/usr/bin/env python3

import argparse
import os
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("--collections", nargs="+", type=str, required=True, help="the collection names")

args, unknown = parser.parse_known_args()

# Iterate over the [name]=[path] pairs
for name in args.collections:
	subprocess.run("./index.sh " + name, shell=True)
