#!/usr/bin/env python3

import argparse
import json
import subprocess

print("Searching...")

parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True, help="the json input")

args, unknown = parser.parse_known_args()

subprocess.run("./search.sh {} {} {} {}".format(args.json["collection"]["name"], args.json["topic"]["path"], args.json["topic"]["format"], args.json["top_k"]), shell=True)